--
-- TABLE COACH.
--
DROP TABLE IF EXISTS `COACH`;
create table COACH (
  COACH_ID bigint NOT NULL AUTO_INCREMENT,
  COACH_NAME varchar(255),
  primary key (COACH_ID)
) ENGINE=INNODB;

--
-- TABLE TEAM.
--
DROP TABLE IF EXISTS `TEAM`;
create table TEAM (
  TEAM_ID bigint(20) NOT NULL AUTO_INCREMENT,
  COACH_ID bigint(20) NOT NULL,
  TEAM_NAME varchar(255) NOT NULL,
  NB_WON integer,
  NB_LOST integer,
  NB_PLAYED integer,
  primary key (TEAM_ID),
  INDEX team_coach (COACH_ID),
  FOREIGN KEY (COACH_ID) REFERENCES COACH(COACH_ID)  
) ENGINE=INNODB;

--
-- TABLE PLAYER.
--
DROP TABLE IF EXISTS `PLAYER`;
create table PLAYER (
  PLAYER_ID bigint(20) NOT NULL AUTO_INCREMENT,
  PLAYER_NAME varchar(255) NOT NULL,
  PLAYER_NUMBER integer,
  BIRTHDAY timestamp,
  HEIGHT float,
  WEIGHT float,
  TEAM_ID bigint,
  primary key (PLAYER_ID),
  INDEX player_team (TEAM_ID),
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
) ENGINE=InnoDB;

--
-- TABLE GAME
--
DROP TABLE IF EXISTS `GAME`
create table GAME (
  GAME_ID bigint NOT NULL AUTO_INCREMENT,
  AWAY_TEAM_SCORE integer,
  HOME_TEAM_SCORE integer,
  GAME_DATE timestamp,
  PLAYER_ID bigint,
  HOME_TEAM_ID bigint,
  AWAY_TEAM_ID bigint,
  primary key (GAME_ID),
  FOREIGN KEY (HOME_TEAM_ID) REFERENCES TEAM(TEAM_ID),
  FOREIGN KEY (AWAY_TEAM_ID) REFERENCES TEAM(TEAM_ID),
  FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(PLAYER_ID)
) ENGINE=InnoDB;



